spring.application.name=apigateway
server.port=8080
# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Register Gateway with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=additionservice

spring.cloud.gateway.routes[0].uri=lb://ADDITIONSERVICE

spring.cloud.gateway.routes[0].predicates[0]=Path=/addition/

spring.cloud.gateway.routes[1].id=multiplicationservice

spring.cloud.gateway.routes[1].uri=lb://MULTIPLICATIONSERVICE

spring.cloud.gateway.routes[1].predicates[0]=Path=/multiplication/